# fly.toml app configuration file generated for client-quiet-surf-2481 on 2025-09-21T14:17:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'client-quiet-surf-2481'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  BACKEND_URL = "https://server-nameless-star-9223.fly.dev"

